# Generated by Django 5.2.6 on 2025-10-02 16:13


from django.db import migrations, models

# ⚙️ Imports:
# - `migrations` handles database schema changes.
# - `models` gives access to Django field types like CharField, TextField, ImageField, etc.



class Migration(migrations.Migration):
     # Ei class ta ekta migration define kore (mane database e ki change hobe).

    dependencies = [
        ('authentication', '0001_initial'),
         # agey authentication app er 0001_initial migration ta run hobe,
        # tarpor ei migration ta apply hobe.
    ]

    operations = [
        # Ei list e sob change likha hoy – jemon field add, delete, modify etc.
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        # bio field add hocche. Optional rakha hoise (blank & null True).
        # Max length 500 character.
        
        migrations.AddField(
            model_name='customuser',
            name='brand_size',
            field=models.CharField(blank=True, choices=[('startup', 'Startup'), ('small', 'Small Business'), ('medium', 'Medium Business'), ('large', 'Large Corporation')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('brand', 'Brand'), ('influencer', 'Influencer'), ('admin', 'Admin')], default='influencer', max_length=10),
        ),
    ]
# user_type field update hoise – ekhon 3 type:
        # brand, influencer, admin.