# Generated by Django 5.2.6 on 2025-10-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_bio_customuser_brand_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='niche',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tiktok_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
